### ISSUE TITLE
Produce sorted rules according to key

### ISSUE THREAD

**Issue by gtoptsid** [openSUSE/polkit-default-privs#3]
The current code (in [chkstat-polkit#L70)](https://github.com/openSUSE/polkit-default-privs/blob/master/chkstat-polkit#L70) uses the keyword "each" to traverse the values in the hash. This results in a random traversal of the hash and produces different contents everytime even when no rule has changed. It does not have any effect on the function of polkit but it makes it difficult to see what the differences are (and is annoying for the few of us that have /etc under revision control).
```
for i in $(seq 1 5); do
    set_polkit_default_privs
    md5sum /etc/polkit-1/rules.d/90-default-privs.rules
done
```
The above bash snippet can be used to test this behavior.

I tried to change the code so that it respects the order of the rules in the polkit-default-privs.X files but with my limited perl-fu, i couldn't make it work so i settled for sorted key order.
```
--- chkstat-polkit.orig	2019-02-04 11:44:13.450418190 +0200
+++ chkstat-polkit	2019-02-04 19:27:46.071957137 +0200
@@ -67,7 +67,8 @@
 
 
 my $rules = '';
-while (my ($privilege, $perms) = each %to_set) {
+foreach my $privilege (sort keys %to_set) {
+	my $perms = $to_set{$privilege};
 	my @p = @$perms;
 	$rules .= sprintf("\t\t'%s':\n\t\t\t[ '%s', '%s', '%s' ],\n", $privilege, $p[0], $p[1], $p[2]);
 }
```
I use the above version locally for some time now and it seems to work but of course there may be a better way to achieve this. 

Do you think it is useful to always produce the same content or it is a niche feature that isn't worth the trouble ?

**Comment by mgerstner** [comment]
Good finding, thanks for the suggestion. We will push this to openSUSE:Factory, will be part of Tumbleweed in a while.
